development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:50f617f859beaa49e4ae79a0560235ca@tarpon.redistogo.com:11212/
  channel_prefix: instatalk_production
